### ISSUE TITLE
Left nav of Feeds page - For Developers list of links order needs to match order on webpage

### ISSUE THREAD

**Issue by lisa-usgs** [usgs/earthquake-event-ws#102]

**Comment by lisa-usgs** [comment]
Re-ordered left nav items to match order in body of webpage.
Preview at http://static-earthquake.cr.usgs.gov/earthquakes/feed/.
I've not committed this yet.

**Comment by ehunter-usgs** [comment]
It looks like one of the .linklist  blocks is indented, while the other is not. I would suggest adding the .no-style to the first .linklist so that it is not indented.

**Comment by lisa-usgs** [comment]
Good catch!  Fixed.
I think my next step is to commit and merge this so it ends up on the production servers.  Then Eric will have to change something so that the left nav and index file show up from the static directory rather than the app.  Issue # 100 is related and will be merged at the same time.

**Comment by lisa-usgs** [comment]
Before the new Feeds static main page goes public, the left nav on the app pages and on the static main page need to match and work correctly.  See the static page at http://static-earthquake.cr.usgs.gov/earthquakes/feed/

**Comment by lisa-usgs** [comment]
Superseded by [#173](https://github.com/usgs/earthquake-event-ws/issues/173)
