### ISSUE TITLE
Add CAP information to ATOM feeds

### ISSUE THREAD

**Issue by jmfee-usgs** [usgs/earthquake-event-ws#107]
Requested via EHP contact form:
> I'm trying to incorporate your ATOM feeds into an alerting application that uses the CAP format. According to your website, you are supporting the CAP protocol: 
> http://earthquake.usgs.gov/earthquakes/catalogs/cap/
> 
> However, the feeds do not conform to the actual CAP standard as best as I can tell. For example, there is no <georss:point> tag in CAP 1.2.
> 
> Also, the many cap-related tags such as urgency, severity, and certainty are missing from the feeds.

To support this request we'd need to add properties to "cap" products that include the alerts, and include them in the fdsn index.  We could then update the ATOM (and possibly GeoJSON) summary formats.

**Comment by wngroves** [comment]
Any movement on this?

**Comment by jmfee-usgs** [comment]
Not yet, this depends on a couple related changes that are not yet scheduled.

**Comment by llastowka-usgs** [comment]
This is going to be a won't fix as we are moving towards standardizing on our other feed types (geojson, etc).  Sorry for any inconvenience.
