### ISSUE TITLE
Updated Region Search Description

### ISSUE THREAD

**Issue by emartinez-usgs** [usgs/earthquake-event-ws#115]
The small grey text that describes the custom regions needs some improvement. Since it is valid for a user to specify both a rectangle and a circle, the description text should reflect both when both are set. Longitude regions should be [min, max]. Consider:

```
Rectangle
- [24.6, 50.0] Latitude
- [-125.0, -65.0] Longitude
Circle
- (34.0, -118.0) Center
- 50 km Radius
```

**Comment by ehunter-usgs** [comment]
This is done.
