### ISSUE TITLE
custom radio should be selected

### ISSUE THREAD

**Issue by llastowka-usgs** [usgs/earthquake-event-ws#119]
When going back to search form from custom mag value search results on map and list, the 2.5+ button is selected and not the custom.  Saw this on Rob's machine and reproduced on mine. 

![image 3](https://cloud.githubusercontent.com/assets/1771126/12859058/f3e5ea36-cc10-11e5-910c-4662ad374a39.png)

**Comment by ehunter-usgs** [comment]
It looks like this same problem exists for all of the basic options:
 - magnitude
 - date & time
 - geographic region

**Comment by ehunter-usgs** [comment]
*For Testing*

First option selected (2.5+ Magnitude, Past 7 Days, World)
http://localhost:9060/earthquakes/search/#%7B%22feed%22%3A%221455830816958%22%2C%22sort%22%3A%22newest%22%2C%22mapposition%22%3A%5B%5B-85%2C0%5D%2C%5B85%2C360%5D%5D%2C%22viewModes%22%3A%7B%22help%22%3Afalse%2C%22list%22%3Atrue%2C%22map%22%3Atrue%2C%22settings%22%3Afalse%7D%2C%22autoUpdate%22%3Afalse%2C%22search%22%3A%7B%22id%22%3A%221455830816958%22%2C%22name%22%3A%22Search%20Results%22%2C%22isSearch%22%3Atrue%2C%22params%22%3A%7B%22starttime%22%3A%222016-02-11%2000%3A00%3A00%22%2C%22minmagnitude%22%3A2.5%2C%22endtime%22%3A%222016-02-18%2023%3A59%3A59%22%2C%22orderby%22%3A%22time%22%7D%7D%7D


Second option selected (4.5+ Magnitude, Past 30 Days, Conterminous U.S.)
http://localhost:9060/earthquakes/search/#%7B%22feed%22%3A%221455830790206%22%2C%22sort%22%3A%22newest%22%2C%22mapposition%22%3A%5B%5B24.6%2C-125%5D%2C%5B50%2C-65%5D%5D%2C%22viewModes%22%3A%7B%22help%22%3Afalse%2C%22list%22%3Atrue%2C%22map%22%3Atrue%2C%22settings%22%3Afalse%7D%2C%22autoUpdate%22%3Afalse%2C%22search%22%3A%7B%22id%22%3A%221455830790206%22%2C%22name%22%3A%22Search%20Results%22%2C%22isSearch%22%3Atrue%2C%22params%22%3A%7B%22starttime%22%3A%222016-01-19%2000%3A00%3A00%22%2C%22maxlatitude%22%3A50%2C%22minlatitude%22%3A24.6%2C%22maxlongitude%22%3A-65%2C%22minlongitude%22%3A-125%2C%22minmagnitude%22%3A4.5%2C%22endtime%22%3A%222016-02-18%2023%3A59%3A59%22%2C%22orderby%22%3A%22time%22%7D%7D%7D


Third option selected (all custom options selected)
http://localhost:9060/earthquakes/search/#%7B%22feed%22%3A%221455831021624%22%2C%22sort%22%3A%22newest%22%2C%22mapposition%22%3A%5B%5B19.643%2C-125%5D%2C%5B50%2C-65%5D%5D%2C%22viewModes%22%3A%7B%22help%22%3Afalse%2C%22list%22%3Atrue%2C%22map%22%3Atrue%2C%22settings%22%3Afalse%7D%2C%22autoUpdate%22%3Afalse%2C%22search%22%3A%7B%22id%22%3A%221455831021624%22%2C%22name%22%3A%22Search%20Results%22%2C%22isSearch%22%3Atrue%2C%22params%22%3A%7B%22starttime%22%3A%222016-01-19%2000%3A00%3A00%22%2C%22maxlatitude%22%3A50%2C%22minlatitude%22%3A19.643%2C%22maxlongitude%22%3A-65%2C%22minlongitude%22%3A-125%2C%22minmagnitude%22%3A4.5%2C%22endtime%22%3A%222016-02-11%2023%3A59%3A59%22%2C%22maxmagnitude%22%3A5.5%2C%22orderby%22%3A%22time%22%7D%7D%7D
