### ISSUE TITLE
Missing minradius parameter

### ISSUE THREAD

**Issue by jmfee-usgs** [usgs/earthquake-event-ws#120]
When the minradius advanced option was removed from the search form, it was incorrectly also removed from the web service:
    https://github.com/usgs/earthquake-event-ws/commit/18fd6ccac50a7f5e457c96b0b93c75842f0d4be2

This parameter is part of the FDSN specification and should be supported (and should arguably also be available as an advanced option on the search form).

**Comment by crotwell** [comment]
No longer allowing minradius breaks SOD for users doing point-distance event queries. Since I have made the USGS FDSNEvent server the default for SOD, it would be really nice if you could re-enable the minradius query parameter.

thanks,Philip

**Comment by jmfee-usgs** [comment]
The minradiuskm parameter still has some issues, and at least needs to be readded to the FDSNQuery php class
