### ISSUE TITLE
Advanced options should be shown by default when set

### ISSUE THREAD

**Issue by emartinez-usgs** [usgs/earthquake-event-ws#121]
If a search has been performed (containing advanced options) and the user is on the map/list and they click the button from the settings panel to perform an archive search, the search page should expand any collapsable section that does not have the default value specified.

To reproduce:

Go to search page.
Create a search and include the "DYFI" product type.
Execute the search and view the results on the Map/List.
Return to the search page by clicking the Archive Search button in the settings panel.
Observe the "Advanced Options" and "Product Type" collapsable sections are still collapsed.

Expect:
"Advanced Options" and "Product Type" collapsable sections should be expanded by default.

**Comment by jmfee-usgs** [comment]
region parameters do not apply for this change (they are shown by the basic region description)

**Comment by jmfee-usgs** [comment]
Having this as a separate loop seems redundant with the existing checks for several of these fields in `bindModel` and `bindModelUpdate`.  Update those methods to also expand the advanced options section, and add a check at the end of `bindModel` for any remaining fields not already checked.
