### ISSUE TITLE
better clarify Conterminous U.S.

### ISSUE THREAD

**Issue by llastowka-usgs** [usgs/earthquake-event-ws#123]
We can add text to clarify this is approximate until we add in the admin region in summary.  Change text to Rectangular box around Conterminous US?

**Comment by jmfee-usgs** [comment]
Use disclaimer (check for template disclaimer best practice):

"Conterminous U.S. refers to a rectangular region including the lower 48 states and surrounding areas which are outside the Conterminous U.S."
