### ISSUE TITLE
Scenario Routing

### ISSUE THREAD

**Issue by emartinez-usgs** [usgs/earthquake-event-ws#147]
The following routes need to be added to squid routing for scenario support. These should all route to the application class of servers within a node.

Not all may work just yet, but these are unadvertised so nobody should be complaining about 404s either...

- /scenarios/eventpage
- /scenarios/feed
- /fdsnws/scenario/1
- /scenarios/map
- /scenario/product
- /scenarios/search

**Comment by emartinez-usgs** [comment]
Merge request #164 on gitlab:hazdev/puppet

**Comment by jmfee-usgs** [comment]
Merged #164 on gitlab:hazdev/puppet.
