### ISSUE TITLE
Scenario Database Replication

### ISSUE THREAD

**Issue by emartinez-usgs** [usgs/earthquake-event-ws#149]
Update puppet configuration to replicate scenarios database. Apply puppet on dev and sync database to start replication.

**Comment by emartinez-usgs** [comment]
Merge request #164 on gitlab:hazdev/puppet

**Comment by jmfee-usgs** [comment]
Merged gitlab:hazdev/puppet#165, close once deployed to dev.

**Comment by emartinez-usgs** [comment]
Deployed to dev.
