### ISSUE TITLE
Missing event type in geojson summary feed

### ISSUE THREAD

**Issue by ehunter-usgs** [usgs/earthquake-event-ws#157]
Type should be "earthquake", see the detail feed excerpt below. 

http://localhost:9060/fdsnws/scenario/1/query.geojson?starttime=2016-01-25%2000:00:00&endtime=2016-02-24%2023:59:59&minmagnitude=2.5&orderby=time

Summary Feed:
`type: "",`

Detail Feed:
`type: "earthquake",`

**Comment by ehunter-usgs** [comment]
This seems to be fixed.

**Comment by ehunter-usgs** [comment]
This is only an issue for scenario feeds

**Comment by emartinez-usgs** [comment]
Should we remove the label "wontfix" ?
