### ISSUE TITLE
Add "Scenario" text to scenario feed specific pages

### ISSUE THREAD

**Issue by ehunter-usgs** [usgs/earthquake-event-ws#163]
For all the feed specific pages:
 - atom
 - kml
 - spreadsheet
 - quakeml
 - geojson

make sure that when the word "earthquake" is used that it is prepended with the word "scenario". This means updating the feed links in the right column on the feed specific pages.

"Significant Earthquakes" --> "Significant Scenario Earthquakes"

**Comment by emartinez-usgs** [comment]
Seems to re-introduce links at top of page in scenario mode. See review comments on PR.
