### ISSUE TITLE
bug on search page time inputs

### ISSUE THREAD

**Issue by jmfee-usgs** [usgs/earthquake-event-ws#165]
In safari and firefox, possibly others besides chrome, the date inputs are filled with NaNs instead of dates.

**Comment by ehunter-usgs** [comment]
I started looking into this and it has to do with the string formatted date being passed into Formatter.formatDateTime()

Chrome can handle, new Date("2016-3-2")
Firefox and Safari need it to look like, new Date("2016-03-02")
