### ISSUE TITLE
Change how event redirects work.

### ISSUE THREAD

**Issue by jmfee-usgs** [usgs/earthquake-event-ws#176]
FDSNEventWebService currently accepts a redirect parameter, but redirects when an event is not found rather than at a specific point in time.
https://github.com/usgs/earthquake-event-ws/blob/master/src/lib/classes/fdsn/FDSNEventWebService.class.php#L41

This occasionally leads to broken links when a feed response is cached for 1 day (event > 30 days old) and then archived before the feed expiration.

One potential solution is to configure a redirect age, so events older than the specified age automatically redirect.

**Comment by ehunter-usgs** [comment]
@jmfee-usgs How do we know the event's age without making a request? I don't understand how we would setup a redirect without knowing more about the event?

**Comment by jmfee-usgs** [comment]
We currently redirect only when an event is not found:
https://github.com/usgs/earthquake-event-ws/blob/99514296c76db66e81127da9a63a62e7d8eb7242/src/lib/classes/fdsn/FDSNEventWebService.class.php#L143

https://github.com/usgs/earthquake-event-ws/blob/99514296c76db66e81127da9a63a62e7d8eb7242/src/lib/classes/fdsn/FDSNEventWebService.class.php#L326

This should optionally configure a redirect age (30 days), and when redirect mode is enabled and if an event is found but older than the redirect age, use the existing redirect logic...
