### ISSUE TITLE
Update left nav of Search page to use EQ section nav instead of Feeds nav

### ISSUE THREAD

**Issue by lisa-usgs** [usgs/earthquake-event-ws#178]
http://earthquake.usgs.gov/earthquakes/search/

Should use the left nav seen at http://earthquake.usgs.gov/earthquakes/errata.php since Search Earthquake Catalog is one of the main listings in the Earthquake section (see http://earthquake.usgs.gov/earthquakes/) instead of using the Feeds & Notifications left nav that is has now.

**Comment by ehunter-usgs** [comment]
This will be handled by #181

**Comment by ehunter-usgs** [comment]
This will not be handled by #181 

I was confused because the navigation at `/earthquakes/feed/` is not the navigation that is stored in `earthquake-website /src/htdocs/earthquakes/feed/_navigation.inc.php`

**Comment by lisa-usgs** [comment]
Exactly!  There are two different left navs, and the one on the static server is the correct one.
