### ISSUE TITLE
Update references to policy.php

### ISSUE THREAD

**Issue by lisa-usgs** [usgs/earthquake-event-ws#180]
#This page is now included as part of the ComCat Documentation at:
http://earthquake.usgs.gov/data/comcat/ (3 separate pages)

There is already a link to the ComCat Documentation in the Earthquakes section left nav, so I the removed the Glossary link in the Feeds section nav and on the Feeds & Notifs main page. (6/13/2016).

... and the policy.php file is now a static page.

**Comment by ehunter-usgs** [comment]
@lisa-usgs does policy.php still exist? 

http://earthquake.usgs.gov/earthquakes/feed/v1.0/policy.php

**Comment by ehunter-usgs** [comment]
#184 is already handling changes for glossary.php
