### ISSUE TITLE
Update _navigation.inc.php file to match the static file in /earthquakes/feed/_navigation.inc.php

### ISSUE THREAD

**Issue by lisa-usgs** [usgs/earthquake-event-ws#181]
The app uses a left nav file that's wrapped in the app package, so it will have to be removed from that file too, or you can modify the app package to use the static left navigation file.

**Comment by ehunter-usgs** [comment]
@lisa-usgs does policy.php still exist?

http://earthquake.usgs.gov/earthquakes/feed/v1.0/policy.php

**Comment by lisa-usgs** [comment]
It's now a static webpage and it lives in http://earthquake.usgs.gov/earthquakes/feed/policy.php.  The links on the other static webpages under /feed/ already use that URL, but I think the app links go to the app file still.

**Comment by ehunter-usgs** [comment]
If this were updated, how would you navigate to the documentation for all of the different feed options?
![screen shot 2016-09-20 at 4 56 40 pm](https://cloud.githubusercontent.com/assets/1932750/18691828/55efa528-7f53-11e6-8cff-eaa3acd3e867.png)
