### ISSUE TITLE
Routing for links in /feed/ do not consistently work

### ISSUE THREAD

**Issue by lisa-usgs** [usgs/earthquake-event-ws#182]
If you start on the page http://earthquake.usgs.gov/earthquakes/feed/, then click on a feed, for example, ATOM Syndication, you will be on http://earthquake.usgs.gov/earthquakes/feed/v1.0/atom.php.

That's all good.  But then if you click on Feeds & Notifications at the top of the left nav menu, it brings you to http://earthquake.usgs.gov/earthquakes/feed/v1.0/index.php (which should be deleted from the app package) instead of the static page at http://earthquake.usgs.gov/earthquakes/feed/ where you started.

**Comment by ehunter-usgs** [comment]
@lisa-usgs It looks like someone updated this. If not can you reopen the issue?
