### ISSUE TITLE
Change link to "Additional earthquake information for 'state' on event page

### ISSUE THREAD

**Issue by lisa-usgs** [usgs/earthquake-event-ws#183]
The "Additional earthquake information for..." under "For More Information" is going to the old pages that are no longer maintained and will eventually be deleted.  The new pages are in the form /earthquake/byregion/california.php".

**Comment by jmfee-usgs** [comment]
These links are stored in comcat, and is best addressed by
- adding a link region layer to geoserve
- querying the links dynamically on the event page
- removing the stale links from comcat.
