### ISSUE TITLE
KML Output from Search - EQ symbols are all yellow circles, and legend indicates these are all "Past Week" even though they aren't

### ISSUE THREAD

**Issue by lisa-usgs** [usgs/earthquake-event-ws#186]
Screenshot attached.
![screen shot 2016-08-24 at 9 48 29 am](https://cloud.githubusercontent.com/assets/4162494/17937742/5e3563fe-69e0-11e6-8409-34ea5408dff0.png)

**Comment by jmfee-usgs** [comment]
There is a TODO in the code:
https://github.com/usgs/earthquake-event-ws/blob/master/src/lib/classes/fdsn/KMLFeed.class.php#L266

We probably also need to update the legend to include a white circle labeled "older".
