### ISSUE TITLE
add explicit xml encoding

### ISSUE THREAD

**Issue by jmfee-usgs** [usgs/earthquake-event-ws#205]
Reported via email.  UTF-8 is supposed to be the default encoding for XML but without explicit encoding some parsers generate errors.
- set explicit UTF-8 charset in HTTP content-type header
- add explicit UTF-8 encoding to xml declaration

> HI
> 
> http://earthquake.usgs.gov/fdsnws/event/1/query?endtime=2016-09-23T02:00:00&starttime=2016-09-23T01:00:00
> 
> This query returns invalid XML. I believe it is because the textual
> description has an accent mark on the 'e' in Barthélemy. I think the
> right thing to do in this case is to escape that as &#233; like:
> 
> Saint Barth&#233;lemy
> 
> You may also need to add an encoding statement to the xml declaration like:
> <?xml version="1.0" encoding="UTF-8"?>
> 
> Thanks
> Philip C

**Comment by crotwell** [comment]
Email seems to have converted the char, the e with acute in Saint Barthélemy should be `&#233;` or `&eacute;`
