### ISSUE TITLE
handle content update times more carefully.

### ISSUE THREAD

**Issue by jmfee-usgs** [usgs/earthquake-event-ws#206]
Current time handling converts second times to millisecond times by adding 000.  This works in all cases, except the time 0; which has occurred because of safari file upload bugs.

**Comment by jdbrown-USGS** [comment]
Could you please provide an event that would cause this error. We were unable to reproduce it.

**Comment by jmfee-usgs** [comment]
We've manually removed product sent with a zero update time, because they cause json validation issues.

I think these are the relevant lines, that need to handle the special case where content modified is 0; to only output 0 instead of 0000:

https://github.com/usgs/earthquake-event-ws/blob/5070b614d73a3dbdde338527460aab99673295fc/src/lib/classes/pdl/ProductStorage.class.php#L89
https://github.com/usgs/earthquake-event-ws/blob/5070b614d73a3dbdde338527460aab99673295fc/src/lib/classes/pdl/ProductStorage.class.php#L118
