### ISSUE TITLE
XML Based Atom Feed Format Problems with Malformed UTF-8 Characters

### ISSUE THREAD

**Issue by emartinez-usgs** [usgs/earthquake-event-ws#224]
**Details**: https://geohazards.usgs.gov/pipermail/realtime-feed-users/2017-March/000073.html

This currently seems to affect ATOM, QuakeML, and KML feed types. Check others as well.

**Example**: https://earthquake.usgs.gov/fdsnws/event/1/query.xml?starttime=2017-03-09%2000:00:00&endtime=2017-03-09%2023:59:59&minmagnitude=4.7&maxmagnitude=4.9&orderby=time

**Suggested Fix**: Use either [utf8_encode](http://php.net/manual/en/function.utf8-encode.php) or [utf8_encode_array](https://github.com/usgs/earthquake-event-ws/blob/master/src/lib/lib.inc.php#L67) functions when generating entries for feeds. Be careful not to double-encode or improperly encode values.

**Comment by Leif-W** [comment]
Thanks for filing the bug report.  Wasn't sure I was looking at the correct repository.
