### ISSUE TITLE
search form does not set/preserve list format

### ISSUE THREAD

**Issue by lisa-usgs** [usgs/earthquake-event-ws#229]
For example:
- set listformat to dyfi
- choose search earthquake archives
- run search using DYFI product type
- map/list should use dyfi listformat

**Comment by ehunter-usgs** [comment]
For whoever picks up this ticket, it seems like none of the settings from earthquake-latest-earthquakes are being preserved, to name a few:
 - list/map/settings (view modes)
 - map position
 - list format
 - list sort order
 - restrict list to map
 - map layers
 - overlays
 - time zone
