### ISSUE TITLE
Non-deleted event labeled as deleted

### ISSUE THREAD

**Issue by ehunter-usgs** [usgs/earthquake-event-ws#270]
@mhearne-usgs pointed out that this event was showing up in the summary feed, but the detail feed was returning a 409 status code (indicating it had beed deleted).

https://dev-earthquake.cr.usgs.gov/fdsnws/event/1/query.geojson?includedeleted=true&eventid=ci11129826

Upon looking into it it looks like an association/disassociation bug. 

Southern California sent two origins for this event, "cici11129826" and "ci11129826". Then it looks like a "DELETE" update was sent for "cici11129826". However, in the event web service when pulling detailed information for the still valid "ci11129826" `getEventIdByFullEventId()` returns the eventid for the now deleted "cici11129826" event. Since this product is no longer linked to an event record the detail feed returns a 409, but the "ci11129826" event is still alive and well and should return a detail feed.

**Comment by ehunter-usgs** [comment]
@jmfee-usgs this feels like a familiar bug, should this be a PDL bug?

**Comment by jmfee-usgs** [comment]
This event seems to have the correct status now.
