### ISSUE TITLE
Is your GeoJSON Summary Format generated from JSONSchema?

### ISSUE THREAD

**Issue by pescadorbob** [usgs/earthquake-event-ws#287]
Hello,

I loved how you documented your GeoJSON Format here:
https://github.com/usgs/earthquake-event-ws/blob/6803b71e95a81f93d310fc726922be75e5b64b08/src/htdocs/geojson.php

I was thinking of documenting my project something like that. I wonder if you hand coded that, or if it was done from JSONSchema, e.g.
Please let me know if you can provide insight to the workings of that. Thank you. -Brent

**Comment by emartinez-usgs** [comment]
Hi @pescadorbob - Unfortunately we hand-coded the whole thing. Please let us know if you find a tool that can automate a similar output.
