### ISSUE TITLE
Search by product type includes events with deleted products

### ISSUE THREAD

**Issue by jmfee-usgs** [usgs/earthquake-event-ws#5]
These stored procedures should filter products that have been deleted:

- getEventProductTypes
- getEventProductSources
- getEventIds

**Comment by ehunter-usgs** [comment]
@jmfee-usgs I see this is two years old, do we still want to do this?

**Comment by jmfee-usgs** [comment]
yes

**Comment by jmfee-usgs** [comment]
getEventProductSources is already complete: 
https://github.com/usgs/earthquake-event-ws/blob/master/src/lib/sql/fdsnws/getEventProductSources.sql#L19

getEventIds should not be updated, so IDs that have been deleted are still visible.
https://github.com/usgs/earthquake-event-ws/blob/master/src/lib/sql/fdsnws/getEventIds.sql

Update the where clause for getEventProductTypes to be similar to getEventProductSources
https://github.com/usgs/earthquake-event-ws/blob/master/src/lib/sql/fdsnws/getEventProductTypes.sql#L16

**Comment by hasimpson-usgs** [comment]
Won't fix.  
Fixed by https://github.com/usgs/earthquake-event-ws/blob/master/src/lib/sql/fdsnws/preferredProduct.sql#L5
