### ISSUE TITLE
use standard quakeml event types

### ISSUE THREAD

**Issue by jmfee-usgs** [usgs/earthquake-event-ws#7]
Original report below.  I suspect this is a quarry blast reported via EQXML, which uses a different enumerated set of event types.

From: <baagaard at usgs.gov>
Subject: EHP Website Email - Reporting website problem
Date: March 21, 2014 1:18:55 PM MDT
To: lisa

URL: http://earthquake.usgs.gov/earthquakes/search/
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/33.0.1750.152 Safari/537.36
This error was pointed out to me on the obspy (Python package for seismic processing) mailing list. http://comcat.cr.usgs.gov/fdsnws/event/1/ catalog does not conform to QuakeML standard. Event types "quarry" and "quarry_blast" are not standard enums. The enum is "quarry blast". There may be other errors, but these were pointed out on the email list, and I verified them. Note: The NCEDC seems to be serving the correct enum for these event types. Brad

**Comment by ehunter-usgs** [comment]
What do we want to do about this. Are we reading these types out of the database?  I recognize these from eqxml.

**Comment by jmfee-usgs** [comment]
Isn't this already fixed?
https://github.com/usgs/earthquake-event-ws/blob/master/src/lib/classes/fdsn/QuakemlFeed.class.php#L120
