### ISSUE TITLE
FEMA IPAWS link needs to be updated on CAP Alert main page

### ISSUE THREAD

**Issue by lisa-usgs** [usgs/earthquake-event-ws#90]
http://earthquake.usgs.gov/earthquakes/catalogs/cap/

 "FEMA IPAWS Open Platform for Emergency Networks" link is broken and needs to be updated to:

http://www.fema.gov/integrated-public-alert-warning-system-open-platform-emergency-networks

**Comment by llastowka-usgs** [comment]
@lisa-usgs I think this is a static page issue in the earthquake website (?)

**Comment by lisa-usgs** [comment]
This is part of the feeds app, so although it may be a static page, it's rolled up with an app.  We agreed to remove the main Feeds page from the app yesterday, but that's the only page in the Feeds app that will be taken out.

**Comment by jmfee-usgs** [comment]
Pretty sure this is static content in the earthquake website.

**Comment by emartinez-usgs** [comment]
It looks like this is an old CAP application on the legacy servers. Maybe I'm wrong, but I couldn't find that page in the website htdocs.

**Comment by lisa-usgs** [comment]
So do we no longer create CAP alerts?  If this page needs to be updated because we still do create CAP alerts, what are the updates it needs?  I see that I created this ticket a long time ago in the Jira system, but I don't remember why.

**Comment by jmfee-usgs** [comment]
We still publish CAP alerts via the ATOM feeds, similar to how it is described on that page.  The process that creates the alerts will eventually be updated, to include more information, but the delivery mechanism is the same.

**Comment by lisa-usgs** [comment]
So... this is not mentioned on the new Feeds pages, and I don't think there is a link to it on the legacy system either. Does this need to be added to the Feeds page, at least with a link back to the old page?

**Comment by jmfee-usgs** [comment]
CAP is more of a specific product than a feed; but it is data accessible through the ATOM/GeoJSON feeds.  We can move it when we figure out where that fits in our documentation.  Possibly the usgs/anss-comcat project.

**Comment by llastowka-usgs** [comment]
So we are discontinuing our cap alerts so I guess we should delete the page describing them.
http://earthquake.usgs.gov/earthquakes/catalogs/cap/
Or just not migrate it and it dies with the legacy servers...

**Comment by lisa-usgs** [comment]
OK, I'll not move that page.  Do we have a link to it anywhere that I need to remove?  I don't think so, but if anyone else knows of a link, let me know.

**Comment by emartinez-usgs** [comment]
CAP has been discontinued and legacy systems have been retired. Closing.
