### ISSUE TITLE
Return Distance & Azimuth in Radial Searches

### ISSUE THREAD

**Issue by llastowka-usgs** [usgs/earthquake-event-ws#96]
When performing radial searches it would be helpful if the [comcat, fdsn] search returned distances/azimuths of EQs from search coordinate [center].
GeoJSON is the main format that should support this, since it supports a variable number of properties.

**Comment by emartinez-usgs** [comment]
I'm against this.

Search results should contain information for the earthquake itself, not the earthquake relative to some input parameter. This is more appropriately done in a post-processing step; perhaps as part of libcomcat etc...

There are technical reasons for my objection as well.
